name: SimpleEdit
main: xvqrlz\simpleedit\Loader
version: 1.0.1
api: ["3.0.0-ALPHA7", "3.0.0", "3.0.1"]
author: xvqrlz
website: https://t.me/xvqrlz
description: A simple and optimized WorldEdit plugin for PocketMine-MP

permissions:
  simpleedit.command.pos1:
    description: Allows setting the first position for region selection
    default: op
  simpleedit.command.pos2:
    description: Allows setting the second position for region selection
    default: op
  simpleedit.command.set:
    description: Allows setting blocks in the selected region
    default: op
  simpleedit.command.undo:
    description: Allows undoing the last edit
    default: op
  simpleedit.command.copy:
    description: Allows copying the selected region
    default: op
  simpleedit.command.paste:
    description: Allows pasting the copied region
    default: op
  simpleedit.command.replace:
    description: Allows replacing blocks in the selected region
    default: op
  simpleedit.command.expand:
    description: Allows expanding the selected region
    default: op
  simpleedit.command.contract:
    description: Allows contracting the selected region
    default: op
  simpleedit.command.sphere:
    description: Allows creating a sphere
    default: op
  simpleedit.command.cylinder:
    description: Allows creating a cylinder
    default: op
  simpleedit.command.pyramid:
    description: Allows creating a pyramid
    default: op
  simpleedit.command.spiral:
    description: Allows creating a spiral
    default: op
  simpleedit.command.walls:
    description: Allows creating walls
    default: op
  simpleedit.command.rotate:
    description: Allows rotating the selected region
    default: op
